ITE-6 rewording
in-toto/ITE pull request #44
Opened 2023-02-06 18:02 UTC by adityasaky

This is based on #43, we're having some write issues and it's faster to just switch to a PR I opened.

2023-02-06 18:06 UTC, jhdalek55 requested changes
There's an extra word to be removed in one sentence. Otherwise this is good.

2023-02-06 18:06 UTC, jhdalek55 commented on ITE/6/README.adoc
> +meaning that the types of claims supported up to this point so can continue to
```suggestion
meaning that the types of claims supported up to this point can continue to
```

2023-02-06 18:08 UTC, adityasaky commented on ITE/6/README.adoc
> +meaning that the types of claims supported up to this point so can continue to
Fixed.

2023-02-06 18:10 UTC, jhdalek55 approved these changes

2023-02-07 15:38 UTC, trishankatdatadog approved these changes

2023-02-07 21:30 UTC, SantiagoTorres approved these changes

2023-02-07 21:30 UTC, merged